import = [
"~/.config/theme/alacritty.toml"
]

[window]
padding = { x = 8, y = 8 }
dynamic_padding = true

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 12
